author:
  name: Vincent Assante Di Cupillo
  email: Vadc@vadc-photo.com
  url: www.vadc-photo.com
title: ''
name: əˈklektik
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: ''
color:
  saturation: 0.4048822808545083
  brandStrength: 0.2181201900821179
  rhythmicContrast: 0.08344918955117464
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  lightness: 0.5684158897493035
typography_spectrum: 0.2209279641974717
content_rating:
  adult: false
layout_spectrum: 1
