typography_spectrum: 0.3745259419083595
content_rating:
  adult: false
color:
  saturation: 0.2813283
  brandStrength: 0.8007519
  rhythmicContrast: 0.2142857
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  lightness: 0.768797
layout_spectrum: 0.4226036099717021
author:
  name: Vincent Assante Di Cupillo
  email: Vadc@vadc-photo.com
  url: www.vadc-photo.com
name: əˈklektik
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ''
description: Vincent Assante Di Cupillo
